/* automatically generated by configure */
/* edit configure.in to change version number */
#define HIMOTE_MAJOR_VERSION 5
#define HIMOTE_MINOR_VERSION 3
#define HIMOTE_RELEASE_VERSION 15
#define HIMOTE_EXTRA_VERSION "-dev"
#define HIMOTE_VERSION "5.3.15-dev"
#define HIMOTE_VERSION_ID 50315
